# Site settings
title: "IMITATING NATURE"
description: > 
  A blog about the total synthesis of natural products and organic chemistry. 

author: Angus Robertson
email: johnny@appleseed.com
twitter_username:
github_username:

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robotnoir.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'https//robotnoir.github.io'
  media: 'assets'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
          field:
            element: "checkbox"
            label: "published"
            value: true
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "description"
        field:
          element: "textarea"
          label: "Enter a post description"
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: CURRENT_DATETIME
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
      - name: "categories"
      	fields:
        	element: "multiselect"
            label: "Add categories"
            placeholder: "Choose categories"
            value:
            	- name: "Personal"
                  value: personal
            alterable: true
      - name: "comments"
        field: 
          element: "checkbox"
          label: "Comments?"
          value: false
      
sass:
    style: compressed

exclude: [vendor]
