# Site settings
title: "IMITATING NATURE"
description: > 
  A blog about the total synthesis of natural products and organic chemistry. 

author: Angus Robertson
email: johnny@appleseed.com
twitter_username:
github_username:

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robotnoir.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'https//robotnoir.github.io'
  media: 'assets'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true

sass:
    style: compressed

exclude: [vendor]

